const animation_path = '../../assets/animations/animals/';
const sound_path = '../../assets/sounds/animals';
export const animalList = [
  {
    id: 'butterfly-lottie-animation',
    name: 'Butterfly',
    spanish_name: 'Mariposa',
    animation_path: require(`${animation_path}butterfly-lottie-animation.json`),
    sound: require(`${sound_path}/Butterfly-Wings-Flapping.mp3`),
  },
  {
    id: 'chicken',
    name: 'Chicken',
    spanish_name: 'Gallina',
    animation_path: require(`${animation_path}chicken.json`),
    sound: require(`${sound_path}/Chicken-Clucking.mp3`),
  },
  {
    id: 'cute-owl',
    name: 'Owl',
    spanish_name: 'Buho',
    animation_path: require(`${animation_path}cute-owl.json`),
    sound: require(`${sound_path}/Owl-Coo.mp3`),
  },
  {
    id: 'dog-tail-wag',
    name: 'Dog',
    spanish_name: 'Perro',
    animation_path: require(`${animation_path}dog-tail-wag.json`),
    sound: require(`${sound_path}/Dog.mp3`),
  },
  {
    id: 'fitness-cow',
    name: 'Cow',
    spanish_name: 'Vaca',
    animation_path: require(`${animation_path}fitness-cow.json`),
    sound: require(`${sound_path}/Cow-Mooing.mp3`),
  },
  {
    id: 'just-a-pigeon',
    name: 'Pigeon',
    spanish_name: 'Paloma',
    animation_path: require(`${animation_path}just-a-pigeon.json`),
    sound: require(`${sound_path}/Pidgeons.mp3`),
  },
  {
    id: 'little-chicken',
    name: 'Chick',
    spanish_name: 'Pollito',
    animation_path: require(`${animation_path}little-chicken.json`),
    sound: require(`${sound_path}/Duck-Chickens.mp3`),
  },
  {
    id: 'monkey',
    name: 'Monkey',
    spanish_name: 'Mono',
    animation_path: require(`${animation_path}monkey.json`),
    sound: require(`${sound_path}/Monkey.mp3`),
  },
  {
    id: 'piggy-bank-laughing',
    name: 'Piggy',
    spanish_name: 'Cerdito',
    animation_path: require(`${animation_path}piggy-bank-laughing.json`),
    sound: require(`${sound_path}/Pig-Oinking.mp3`),
  },
  {
    id: 'sheep',
    name: 'Sheep',
    spanish_name: 'Oveja',
    animation_path: require(`${animation_path}sheep.json`),
    sound: require(`${sound_path}/Sheep-Lamb-Bah.mp3`),
  },
  {
    id: 'sleepy-cat',
    name: 'Cat',
    spanish_name: 'Gato',
    animation_path: require(`${animation_path}sleepy-cat.json`),
    sound: require(`${sound_path}/Cat-Cartoon.mp3`),
  },
  {
    id: 'wolf-howling',
    name: 'Wolf',
    spanish_name: '',
    animation_path: require(`${animation_path}wolf-howling.json`),
    sound: require(`${sound_path}/Wolf-Howling.mp3`),
  },
  {
    id: 'turkey',
    name: 'Turkey',
    spanish_name: '',
    animation_path: require(`${animation_path}turkey.json`),
    sound: require(`${sound_path}/Turkey.mp3`),
  },
  {
    id: 'koala',
    name: 'Koala',
    spanish_name: 'Coala',
    animation_path: require(`${animation_path}sleeping-polar-bear.json`),
    sound: require(`${sound_path}/Panda-Bear.mp3`),
  },
  {
    id: 'dolphin',
    name: 'Dolphin',
    spanish_name: '',
    animation_path: require(`${animation_path}dolphin.json`),
    sound: require(`${sound_path}/Dolphin-Chirping.mp3`),
  },
];
